import { AppContent } from "@/types/content";

export const appContent: AppContent = {
  developer: {
    fullName: "Ngọ Viết Hưng",
    role: "Full-Stack Developer (Next.js • Node.js / NestJS • Laravel Livewire • WordPress • AI Tools)",
    shortTitle: "Full-Stack Developer & AI-Assisted Engineer",
    location: "Hà Nội, Việt Nam",
    phone: "0333 246 944",
    phoneRaw: "0333246944",
    email: "ngoviethung0911@gmail.com",
    githubUrl: "https://github.com/Ngohug2003",
    githubDisplay: "github.com/Ngohug2003",
    zaloUrl: "https://zalo.me/0333246944",
    avatarUrl: "/hung_developer_avatar.png",
    cvUrl: "/full-stack-developer-cv-ngo-viet-hung.pdf",
    cvDownloadUrl: "/full-stack-developer-cv-ngo-viet-hung.pdf?download=1",
    cvName: "Full Stack Developer CV - Ngo Viet Hung.pdf",
  },
  navbar: {
    logoText: "Hưng Dev Studio",
    menuItems: [
      { name: "Trang chủ", id: "trang-chu" },
      { name: "Giới thiệu", id: "gioi-thieu" },
      { name: "Dịch vụ", id: "dich-vu" },
      { name: "Dự án", id: "du-an" },
      { name: "Liên hệ", id: "lien-he" },
    ],
    ctaText: "Tư vấn",
  },
  hero: {
    badge: "Website & SEO Partner",
    title: "Thiết kế website chuyên nghiệp giúp doanh nghiệp phát triển",
    description: "Tôi giúp cá nhân, cửa hàng và doanh nghiệp xây dựng landing page, website bán hàng hiện đại, tải cực nhanh, chuẩn SEO và dễ vận hành.",
    ctaPrimary: "Liên hệ tư vấn",
    ctaSecondary: "Xem dịch vụ",
    trustCards: [
      {
        iconName: "Smartphone",
        title: "Responsive",
        subtitle: "Hiển thị đẹp mọi thiết bị",
      },
      {
        iconName: "Search",
        title: "Chuẩn SEO",
        subtitle: "Tối ưu dễ lên top Google",
      },
      {
        iconName: "Zap",
        title: "Tốc độ tối đa",
        subtitle: "Website tải mượt, cực nhanh",
      },
    ],
  },
  problems: {
    badge: "Vấn đề",
    title: "Website của bạn có đang gặp những trở ngại này?",
    description: "Một trang web tải chậm, giao diện cũ kỹ hoặc không chuẩn SEO có thể âm thầm khiến bạn mất đi hàng nghìn khách hàng tiềm năng.",
    problems: [
      {
        iconName: "Zap",
        title: "Tốc độ tải trang chậm",
        desc: "Khách hàng rời đi ngay lập tức nếu trang web mất quá 3 giây để hiển thị đầy đủ thông tin.",
      },
      {
        iconName: "Smartphone",
        title: "Giao diện không tương thích di động",
        desc: "Bố cục lộn xộn, chữ quá nhỏ hoặc nút bấm khó thao tác trên điện thoại di động làm mất điểm tối đa.",
      },
      {
        iconName: "Search",
        title: "Không chuẩn SEO, thiếu người xem",
        desc: "Trang web được thiết kế sơ sài, thiếu tối ưu onpage khiến thương hiệu không thể tiếp cận khách hàng trên Google.",
      },
    ],
  },
  about: {
    badge: "Giới thiệu",
    title: "Tôi là Hưng — Full-stack Developer tại Hà Nội",
    description: "Với hơn 2 năm kinh nghiệm trong thiết kế và phát triển web, tôi mang đến các giải pháp website chuẩn hóa giúp tối đa hóa hiệu quả kinh doanh của bạn.",
    bioText1: "Tôi tin rằng một website xuất sắc không chỉ nằm ở giao diện đẹp, mà cốt lõi phải là tốc độ tải trang nhanh, cấu trúc mã nguồn tối ưu chuẩn SEO và trải nghiệm sử dụng tinh giản trên điện thoại.",
    bioText2: "Kết hợp kỹ thuật lập trình tinh gọn (React/Next.js, Node.js, Laravel) cùng các công cụ AI hiện đại (Codex, Antigravity) để định hình requirement sắc bén, tối ưu kiến trúc và tăng tốc độ bàn giao dự án.",
    focusCards: [
      {
        iconName: "Code",
        title: "Lập trình tối ưu & Ứng dụng AI",
        desc: "Tận dụng AI (Codex, Antigravity) để lên ý tưởng, định hình requirement và tối ưu hóa code sạch chuẩn mực.",
      },
      {
        iconName: "Cpu",
        title: "Hiệu năng ấn tượng",
        desc: "Website phản hồi tức thì, đạt điểm xanh tối đa trên Google PageSpeed Insights.",
      },
      {
        iconName: "ShieldAlert",
        title: "Tối ưu hóa SEO",
        desc: "Cấu trúc HTML chuẩn Semantic giúp bot Google dễ dàng quét và lập chỉ mục nhanh.",
      },
    ],
    skillCategories: [
      {
        id: "frontend",
        tag: "01",
        label: "Frontend",
        iconName: "Layers",
        badgeClass: "bg-blue-500/10 text-blue-400 border-blue-500/20",
        title: "Giao diện người dùng & Trải nghiệm (UI/UX)",
        desc: "Xây dựng web app tốc độ cao, chuẩn Responsive đa thiết bị, tối ưu Core Web Vitals xanh 98+.",
        skills: [
          { name: "Next.js 16 (App Router)", highlight: true },
          { name: "React 19", highlight: true },
          { name: "TypeScript", highlight: true },
          { name: "Tailwind CSS v4", highlight: false },
          { name: "Motion (Framer)", highlight: false },
          { name: "HTML5 / Semantic SEO", highlight: false },
        ],
        highlights: ["PageSpeed 98+", "Micro-animations 120fps", "Zero Layout Shift (CLS)"],
      },
      {
        id: "backend",
        tag: "02",
        label: "Backend",
        iconName: "Server",
        badgeClass: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
        title: "Kiến trúc hệ thống & Cơ sở dữ liệu",
        desc: "Phát triển backend chuyên sâu với Node.js, NestJS, FastAPI (Python), Laravel Livewire và CMS WordPress.",
        skills: [
          { name: "Node.js", highlight: true },
          { name: "NestJS", highlight: true },
          { name: "Laravel & Livewire", highlight: true },
          { name: "FastAPI (Python)", highlight: true },
          { name: "WordPress (CMS)", highlight: true },
          { name: "PostgreSQL / MySQL", highlight: false },
          { name: "Resend Email API", highlight: false },
        ],
        highlights: ["Node.js & NestJS", "Laravel Livewire & WordPress", "FastAPI Python & Resend"],
      },
      {
        id: "cloud",
        tag: "03",
        label: "Cloud",
        iconName: "Cloud",
        badgeClass: "bg-purple-500/10 text-purple-400 border-purple-500/20",
        title: "Hạ tầng đám mây & Vận hành (DevOps)",
        desc: "Tự động hóa CI/CD qua GitHub Actions, triển khai Render & VPS Nginx, lưu trữ ảnh MinIO S3 và Docker hóa.",
        skills: [
          { name: "CI/CD (GitHub Actions)", highlight: true },
          { name: "Docker Container", highlight: true },
          { name: "Render Cloud PaaS", highlight: true },
          { name: "MinIO (S3 Storage)", highlight: true },
          { name: "Linux VPS / Nginx", highlight: false },
          { name: "Vercel / Supabase", highlight: false },
        ],
        highlights: ["Tự động hóa CI/CD Pipeline", "MinIO S3 & Render PaaS", "Docker Container hóa"],
      },
      {
        id: "tools",
        tag: "04",
        label: "Tools & AI",
        iconName: "Wrench",
        badgeClass: "bg-amber-500/10 text-amber-400 border-amber-500/20",
        title: "Bộ công cụ phát triển & AI Workflow",
        desc: "Ứng dụng AI (Codex, Antigravity) để lên ý tưởng, định hình requirement và tối ưu mã nguồn dự án.",
        skills: [
          { name: "AI Coding (Codex / Antigravity)", highlight: true },
          { name: "Git / GitHub Flow", highlight: true },
          { name: "Figma UI/UX Design", highlight: true },
          { name: "VS Code / Turbopack", highlight: false },
          { name: "Postman API Test", highlight: false },
          { name: "Telegram Bot Alert", highlight: false },
        ],
        highlights: ["AI Coding & Requirement Shaping", "Chuyển Figma pixel-perfect", "Quy trình Git Flow chuẩn"],
      },
    ],
    profileCard: {
      name: "Ngọ Viết Hưng",
      role: "Freelance UI/UX & Web Developer",
      location: "Hà Nội, Việt Nam",
      avatarUrl: "/hung_developer_avatar.png",
      stats: [
        { label: "Tốc độ chuẩn", value: "< 0.8s", subtext: "PageSpeed xanh 98+" },
        { label: "Tỷ lệ hài lòng", value: "100%", subtext: "Hỗ trợ trọn vòng đời" },
      ],
      coreTechBadges: [
        "Next.js 16",
        "React 19",
        "Node.js",
        "NestJS",
        "Laravel Livewire",
        "FastAPI (Python)",
        "WordPress",
        "AI Workflow (Codex/Antigravity)",
        "CI/CD Pipeline",
        "Docker",
        "MinIO (S3)",
        "PostgreSQL",
      ],
      qualityPledge: "Cam kết chất lượng: Bàn giao mã nguồn sạch sẽ, không mã hoá, dễ dàng mở rộng và tối ưu chuyển đổi khách hàng.",
    },
  },
  services: {
    badge: "Dịch vụ",
    title: "Giải pháp thiết kế web tinh gọn & hiệu quả",
    description: "Cung cấp các gói dịch vụ được tối ưu hóa cho từng nhu cầu cụ thể, đảm bảo chi phí hợp lý và hiệu quả đầu tư cao nhất.",
    services: [
      {
        name: "Gói Landing Page",
        price: "Từ 3.500.000đ",
        desc: "Tối ưu hóa mục tiêu chuyển đổi bán hàng cho một trang sản phẩm đơn lẻ hoặc chiến dịch quảng cáo.",
        popular: false,
        features: [
          "Thiết kế 1 trang độc quyền chuyên nghiệp",
          "Responsive đầy đủ trên di động/máy tính",
          "Tích hợp biểu mẫu và Google Sheets nhận data",
          "Tối ưu hóa tốc độ tải trang cực nhanh",
          "Tặng 1 năm tên miền quốc tế và hosting",
        ],
        ctaText: "Bắt đầu ngay",
        illustrationType: "landing",
      },
      {
        name: "Website Doanh Nghiệp / Bán Hàng",
        price: "Từ 6.500.000đ",
        desc: "Phù hợp cho các cửa hàng, doanh nghiệp dịch vụ muốn giới thiệu sản phẩm và tăng uy tín thương hiệu.",
        popular: true,
        popularBadge: "Phổ biến",
        features: [
          "Bố cục nhiều trang: Trang chủ, Sản phẩm, Liên hệ...",
          "Hệ thống quản lý sản phẩm tinh gọn, dễ dùng",
          "Kết nối nút đặt mua nhanh, Zalo, Messenger",
          "Tối ưu SEO onpage từng bài viết, sản phẩm",
          "Bàn giao tài liệu hướng dẫn quản trị chi tiết",
        ],
        ctaText: "Nhận báo giá",
        illustrationType: "ecommerce",
      },
      {
        name: "Tối ưu SEO & Tăng tốc web",
        price: "Từ 2.000.000đ",
        desc: "Dịch vụ tối ưu lại mã nguồn có sẵn để nâng điểm PageSpeed và gia tăng thứ hạng tìm kiếm tự nhiên.",
        popular: false,
        features: [
          "Nén ảnh thế hệ mới, tối ưu hóa CSS/JS",
          "Nâng điểm Google PageSpeed Insights lên 90+",
          "Cấu trúc lại thẻ H1-H6, sitemap, meta tags",
          "Xử lý lỗi bảo mật SSL/HTTPS, chuyển hướng",
          "Báo cáo chi tiết trước và sau khi tối ưu",
        ],
        ctaText: "Tối ưu ngay",
        illustrationType: "seo",
      },
    ],
  },
  workflow: {
    badge: "Quy trình",
    title: "Quy trình làm việc 5 bước chuyên nghiệp",
    description: "Quy trình làm việc rõ ràng, nhanh gọn giúp bạn dễ dàng theo sát tiến độ và nhận sản phẩm đúng hẹn.",
    steps: [
      {
        number: "01",
        title: "Tư vấn & Báo giá",
        desc: "Trao đổi chi tiết về ý tưởng dự án, đối tượng khách hàng, chức năng cần có và chốt chi phí triển khai phù hợp nhất.",
        details: ["Khảo sát yêu cầu", "Lập dự toán chi tiết"],
      },
      {
        number: "02",
        title: "Phác thảo Wireframe",
        desc: "Thiết kế bố cục nội dung cơ bản của trang web bằng hình vẽ đen trắng giúp bạn duyệt trước cấu trúc trước khi code.",
        details: ["Dàn trang nội dung", "Duyệt wireframe"],
      },
      {
        number: "03",
        title: "Lập trình mã nguồn",
        desc: "Bắt tay vào code giao diện tỉ mỉ theo đúng chuẩn responsive, đảm bảo tốc độ tải mượt mà và tối ưu hóa SEO.",
        details: ["Lập trình React/Next.js", "Tối ưu di động"],
      },
      {
        number: "04",
        title: "Kiểm thử & Tối ưu",
        desc: "Tiến hành rà soát lỗi trên các thiết bị, tối ưu điểm số tốc độ tải trang trên Google PageSpeed Insights đạt mức xanh.",
        details: ["Test responsive", "Tăng tốc độ load"],
      },
      {
        number: "05",
        title: "Bàn giao & Hướng dẫn",
        desc: "Cấu trúc tên miền, hosting chạy chính thức, gửi tài liệu hướng dẫn và video giúp bạn làm chủ website dễ dàng.",
        details: ["Chạy chính thức", "Bàn giao mã nguồn"],
      },
    ],
  },
  portfolio: {
    badge: "Dự án tiêu biểu",
    title: "Những sản phẩm đã hoàn thiện",
    description: "Tổng hợp các dự án website, landing page thực tế được tối ưu hóa giao diện và cấu trúc chuẩn chuyển đổi cao.",
    categories: ["Tất cả", "Landing Page", "Website Bán Hàng", "Web Doanh Nghiệp"],
    projects: [
      {
        title: "SHOPZONE",
        category: "E-Commerce",
        desc: "Cửa hàng phụ kiện âm thanh cao cấp với tính năng lọc sản phẩm nhanh, thanh toán mượt mà và giao diện tối giản.",
        imageAlt: "Shopzone e-commerce preview",
        features: ["Tốc độ load dưới 1.5s", "Hỗ trợ thanh toán nhanh", "Đạt 98 điểm di động"],
        ctaText: "Xem dự án",
        techStack: ["Next.js", "Tailwind CSS", "Zustand"],
      },
      {
        title: "VELOCE CHRONO",
        category: "Landing Page",
        desc: "Trang sản phẩm đồng hồ titan cao cấp với các hiệu ứng chuyển động mượt mà, cấu trúc tăng tối đa chuyển đổi mua hàng.",
        imageAlt: "Veloce chrono preview",
        features: ["Responsive 100%", "Tối ưu hóa chuyển đổi", "Tải trang tức thì"],
        ctaText: "Xem dự án",
        techStack: ["React", "Framer Motion", "Tailwind CSS"],
      },
      {
        title: "HƯNG DEV STUDIO",
        category: "Web Doanh Nghiệp",
        desc: "Hệ thống website thương hiệu và nền tảng dịch vụ tối ưu SEO, tự động hóa quản trị và vận hành trên VPS.",
        imageAlt: "Hung Dev Studio preview",
        features: ["Tự động triển khai CI/CD", "Chứng chỉ SSL A+", "Sao lưu đám mây định kỳ"],
        ctaText: "Xem dự án",
        techStack: ["Next.js 16", "TypeScript", "Docker"],
      },
      {
        title: "NEXUS ARCHITECTURE",
        category: "Web Doanh Nghiệp",
        desc: "Trang giới thiệu studio kiến trúc cao cấp phong cách tối giản Bắc Âu, bố cục thoáng đãng và tối ưu tốc độ 100/100.",
        imageAlt: "Nexus Architecture preview",
        features: ["Phong cách tối giản Bắc Âu", "Tải trang dưới 0.6s", "Chuẩn SEO Google 100%"],
        ctaText: "Xem dự án",
        techStack: ["Next.js", "Tailwind CSS", "Motion"],
      },
    ],
    bannerTitle: "Sẵn sàng sở hữu website chuẩn SEO của riêng bạn?",
    bannerDesc: "Hãy để tôi giúp bạn xây dựng một trang web hiện đại, tải nhanh và mang lại hiệu quả kinh doanh thực tế.",
    bannerCta: "Bắt đầu ngay",
  },
  projectShowcase: {
    badge: "TECHNICAL PORTFOLIO & RECRUITER SHOWCASE",
    title: "Dự Án Thực Chiến & Hồ Sơ Kỹ Năng",
    subtitle: "Tổng hợp các sản phẩm đã hoàn thiện cùng danh mục kỹ năng lập trình Full-Stack.",
    recruiterNote: "Tôi tập trung vào việc tạo ra sản phẩm hoàn chỉnh: kiến trúc sạch (Clean Architecture), 100% Type-Safe với TypeScript, tối ưu Core Web Vitals xanh 98+, triển khai CI/CD tự động trên VPS/Cloud và tận dụng AI Workflow (Codex, Antigravity) để tăng tốc độ bàn giao.",
    tabs: [
      {
        id: "projects",
        label: "Dự Án Thực Chiến",
        iconName: "FolderKanban",
        description: "Danh mục các sản phẩm website, landing page và web app hoàn thiện",
      },
      {
        id: "profile",
        label: "Hồ Sơ & Kỹ Năng",
        iconName: "UserCheck",
        description: "Thông tin lập trình viên và các nhóm kỹ năng chuyên môn",
      },
    ],
    metrics: [
      { value: "< 0.8s", label: "Tốc độ tải", subtext: "Core Web Vitals chuẩn", iconName: "Zap" },
      { value: "100%", label: "Responsive", subtext: "Pixel-perfect mọi màn hình", iconName: "Smartphone" },
      { value: "98+", label: "PageSpeed", subtext: "Tối ưu hóa Onpage SEO", iconName: "ShieldCheck" },
      { value: "Strict TS", label: "Clean Code", subtext: "Kiến trúc dễ mở rộng", iconName: "Clock" },
    ],
    skillGroups: [
      {
        id: "frontend",
        name: "Frontend Engineering",
        tag: "01",
        badgeClass: "bg-blue-500/10 text-blue-400 border-blue-500/20",
        summary: "Phát triển web app hiện đại, reactive mượt mà và tối ưu chuyển đổi UX.",
        skills: ["Next.js 16 (App Router)", "React 19", "TypeScript", "Tailwind CSS v4", "Motion", "Responsive UI"],
      },
      {
        id: "backend",
        name: "Backend & Systems",
        tag: "02",
        badgeClass: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
        summary: "Thiết kế RESTful APIs, kiến trúc module doanh nghiệp và xử lý dữ liệu.",
        skills: ["Node.js", "NestJS Enterprise", "Laravel & Livewire", "FastAPI (Python)", "WordPress (CMS)", "PostgreSQL / MySQL", "Resend Email API"],
      },
      {
        id: "devops",
        name: "DevOps & Cloud Infrastructure",
        tag: "03",
        badgeClass: "bg-purple-500/10 text-purple-400 border-purple-500/20",
        summary: "Tự động hóa pipeline triển khai, container hóa và lưu trữ tệp tin.",
        skills: ["CI/CD (GitHub Actions)", "Docker Container", "Render Cloud PaaS", "MinIO (S3 Storage)", "Linux VPS / Nginx", "Vercel / Supabase"],
      },
      {
        id: "ai-tools",
        name: "AI-Assisted & Engineering Workflow",
        tag: "04",
        badgeClass: "bg-amber-500/10 text-amber-400 border-amber-500/20",
        summary: "Ứng dụng AI để định hình requirement, sinh mã nhanh và kiểm thử chuyên nghiệp.",
        skills: ["AI Coding (Codex / Antigravity)", "Định hình Requirement & PRD", "Git Flow & CI Hooks", "Figma Design-to-Code", "Postman API Testing"],
      },
    ],
    engineeringStandards: [
      {
        title: "Clean Architecture & Type-Safety",
        desc: "Mã nguồn phân tầng rõ ràng, 100% strict TypeScript không dùng `any`, cấu trúc dễ bảo trì và mở rộng khi team phát triển.",
        iconName: "Cpu",
      },
      {
        title: "Tối ưu Hiệu năng & PageSpeed 98+",
        desc: "Kỹ thuật Server Components, nén ảnh AVIF/WebP, code splitting và loại bỏ hoàn toàn render blocking để đạt điểm xanh tuyệt đối.",
        iconName: "Zap",
      },
      {
        title: "Chu trình CI/CD & Deploy Ổn định",
        desc: "Tích hợp GitHub Actions build GHCR, deploy VPS tự động qua SSH script với cơ chế zero-downtime và rollback tức thì.",
        iconName: "GitBranch",
      },
      {
        title: "Bảo Mật & Tiêu Chuẩn Vận Hành",
        desc: "Cấu hình HTTPS/SSL chuẩn A+, phân quyền biến môi trường an toàn (.env), xác thực CORS và chống tấn công bảo mật web cơ bản.",
        iconName: "ShieldCheck",
      },
    ],
    popularTechFilters: [
      "Tất cả",
      "Next.js",
      "React",
      "Node.js",
      "NestJS",
      "Laravel",
      "FastAPI",
      "WordPress",
      "Docker",
      "TypeScript",
      "CI/CD",
      "MinIO",
    ],
  },
  faq: {
    badge: "FAQ",
    title: "Câu hỏi thường gặp",
    description: "Giải đáp những băn khoăn phổ biến giúp bạn dễ dàng chuẩn bị và phối hợp triển khai dự án website hiệu quả.",
    faqItems: [
      {
        title: "Làm một website hoặc landing page mất bao lâu?",
        content: "Thông thường từ 3–7 ngày làm việc tùy thuộc vào khối lượng nội dung, cấu trúc trang và mức độ phức tạp của dự án.",
        illustrationType: "calendar",
      },
      {
        title: "Tôi chưa chuẩn bị xong nội dung thì có làm được không?",
        content: "Hoàn toàn được. Tôi sẽ hỗ trợ bạn xây dựng khung sườn nội dung cơ bản, định hướng biên soạn bài viết và cấu trúc bố cục tối ưu chuyển đổi.",
      },
      {
        title: "Website có tương thích tốt trên điện thoại di động không?",
        content: "Tất nhiên. Website được thiết kế responsive chuẩn hóa hiển thị trên mọi thiết bị: điện thoại di động, máy tính bảng và màn hình máy tính lớn.",
      },
      {
        title: "Website có được tối ưu để hỗ trợ SEO tốt không?",
        content: "Có. Mã nguồn sẽ được tối ưu onpage kỹ lưỡng bao gồm các thẻ tiêu đề (H1-H6), thẻ meta, sitemap, robots.txt và kết nối Google Search Console.",
      },
      {
        title: "Tôi được hỗ trợ những gì sau khi bàn giao sản phẩm?",
        content: "Tôi hỗ trợ kỹ thuật, khắc phục lỗi phát sinh và cung cấp tài liệu/video hướng dẫn quản trị chi tiết để bạn tự tin làm chủ website.",
      },
      {
        title: "Có thể nâng cấp thêm chức năng sau này không?",
        content: "Có. Kiến trúc website được xây dựng dạng module linh hoạt giúp dễ dàng tích hợp thêm trang blog, giỏ hàng bán hàng nâng cao hoặc hệ thống thanh toán tự động về sau.",
      },
    ],
    supportTitle: "Bạn cần trao đổi thêm?",
    supportDesc: "Tôi sẵn sàng hỗ trợ phản hồi nhanh chóng.",
    supportCta: "Liên hệ tư vấn",
    supportBenefits: [
      "Tư vấn trực tiếp, phản hồi trong 24h",
      "Báo giá minh bạch, rõ ràng từng hạng mục",
    ],
    supportEmail: "ngoviethung0911@gmail.com",
    supportPhone: "0333 246 944",
  },
  contact: {
    badge: "Liên hệ",
    title: "Sẵn sàng xây dựng website của bạn?",
    description: "Hãy chia sẻ thông tin về dự án, tôi sẽ phản hồi và tư vấn giải pháp kỹ thuật tối ưu nhất cho bạn.",
    servicesList: [
      {
        title: "Tư vấn thiết kế Landing Page",
        desc: "Tối ưu hóa tỷ lệ chuyển đổi khách hàng, thiết kế giao diện phù hợp với chiến dịch marketing của bạn.",
      },
      {
        title: "Phát triển Website Bán Hàng",
        desc: "Trưng bày sản phẩm đẹp mắt, kết nối biểu mẫu đặt hàng nhanh chóng và dễ quản lý nội dung sản phẩm.",
      },
      {
        title: "Tối ưu hóa cấu trúc SEO",
        desc: "Tối ưu Onpage chuẩn chỉ, tăng tốc độ tải trang giúp website thân thiện tối đa với bộ máy tìm kiếm.",
      },
    ],
    channels: [
      {
        type: "phone",
        label: "0333 246 944",
        href: "tel:0333246944",
      },
      {
        type: "email",
        label: "ngoviethung0911@gmail.com",
        href: "mailto:ngoviethung0911@gmail.com",
      },
      {
        type: "facebook",
        label: "GitHub Ngohug2003",
        href: "https://github.com/Ngohug2003",
      },
    ],
    serviceOptions: [
      { value: "Tư vấn landing page", label: "Landing Page Chuyển Đổi Cao" },
      { value: "Thiết kế website doanh nghiệp", label: "Website Doanh Nghiệp / Bán Hàng" },
      { value: "Tối ưu SEO & Tốc độ", label: "Tối Ưu SEO & Tốc Độ PageSpeed" },
      { value: "Dự án khác", label: "Tư Vấn Thiết Kế Theo Yêu Cầu" },
    ],
    formTitle: "Đăng ký nhận tư vấn",
    formSubtitle: "Mô tả tóm tắt về yêu cầu dự án, sản phẩm, đối tượng khách hàng và mục tiêu của bạn...",
    formSubmitText: "Gửi yêu cầu tư vấn",
  },
  footer: {
    brandDesc: "Dịch vụ tư vấn thiết kế Landing Page, phát triển website bán hàng tinh gọn và tối ưu hóa cấu trúc SEO cơ bản.",
    email: "ngoviethung0911@gmail.com",
    phone: "0333 246 944",
    facebook: "github.com/Ngohug2003",
    columns: [
      {
        title: "Dịch vụ",
        links: [
          { text: "Landing Page", href: "#dich-vu" },
          { text: "Website Bán Hàng", href: "#dich-vu" },
          { text: "SEO Onpage", href: "#dich-vu" },
        ],
      },
      {
        title: "Liên kết",
        links: [
          { text: "Trang chủ", href: "#" },
          { text: "Giới thiệu", href: "#gioi-thieu" },
          { text: "Quy trình", href: "#quy-trinh" },
          { text: "Câu hỏi", href: "#faq" },
        ],
      },
    ],
    copyright: "© 2026 Ngọ Viết Hưng. Bản quyền đã được bảo hộ.",
    privacyText: "Bảo mật tuyệt đối",
    backToTopText: "Đầu trang",
  },
};
export default appContent;
